### ISSUE TITLE
Link errato in FIUP_Rules.md

### ISSUE THREAD

**Issue by sydernee** [FIUP/Getting-Started#5]
### Descrizione
Nella pagina [FIUP_Rules.md](https://github.com/FIUP/Getting-Started/blob/master/FIUP_Rules.md), il link che punta alle CLOUD FAQ (sezione "Link utili") punta a una pagina non più esistente.

**Comportamento atteso:**
CLOUD FAQ dovrebbe puntare alla pagina https://github.com/FIUP/Getting-Started/blob/master/CLOUD_FAQ.md.

### Informazioni aggiuntive
La issue è semplice e il tag "first-timers-only" prende ispirazione dall'[omonimo progetto](http://www.firsttimersonly.com/): lo scopo è appunto quello di invitare chi non ha mai contribuito in precedenza a partecipare.

**Comment by Giovarco** [comment]
Salve! Vorrei provare a dare una mano. Cercherò di seguire alla lettera le vostre [linee guida](https://github.com/FIUP/Getting-Started/blob/master/CONTRIBUTING.md).

**Comment by fedsib** [comment]
Grazie @Giovarco ottimo lavoro
