### ISSUE TITLE
Informazioni errate in CLOUD_FAQ.md

### ISSUE THREAD

**Issue by sydernee** [FIUP/Getting-Started#7]
Nel file CLOUD_FAQ.md vengono riportate alcune informazioni errate/non più valide e che quindi sono da rettificare.

In particolare, sono _da rimuovere_ le seguenti frasi:

> - ***Ogni quanto viene aggiornato il link pubblico?*** Al momento non c'è una tempestica periodica definita. Solitamente prima e dopo le sessioni d'esame, in casi eccezionali anche prima. Il link pubblico verrà deprecato in un prossimo futuro.

> - ***Ho provato ad aggiungere documenti alla cartella però gli vedono solo chi e stato aggiunto e non gli altri pubblicamente come mai?*** E' corretto. Ciò accade perché il link pubblico punta ad una cartella differente rispetto a quella principale dove la gente viene aggiunta.

>- ***Perché il link e la cartella non sono sincronizzati? Che assurdità è mai questa?*** La soluzione del punto precedente a prima vista può apparire stupida (e in parte lo è). Ma a causa dei nostri circa 800 contatti MEGA da degli errori bizzarri ai quali neanche il team di sviluppo sa trovare una spiegazione. Per questo la struttura del nostro spazio è:
	1. "Materiale FIUP" Cartella dove la gente viene aggiunta via mail
	2. "Materiale FIUP" Cartella separata di backup utilizzata da link pubblico, periodicamente ricreata. 
	
> - ***Mi sfugge ancora il punto della situazione*** A causa dei molti contatti il link della cartella principale non funziona a dovere (non sincronizza la roba), si rende quindi necessaria la trafila spiegata prima per garantire l'accesso a tutti, anche a chi è senza account. 

in quanto il link pubblico non è più disponibile.

Da _rivedere_:
> su MEGA lo spazio gratuito ammonta a 50 GB e le cartelle condivise non erodono il tuo spazio personale

Lo spazio gratuito per i nuovi account ora ammonta  a 15GB (ci sono gli obiettivi, ma presto o tardi scadono tutti) e, cosa ben più importante, **le cartelle condivise erodono lo spazio personale**.

**Comment by fedsib** [comment]
Informazioni ulteriori circa gli obiettivi di MEGA?

**Comment by fedsib** [comment]
https://www.reddit.com/r/megalinks/comments/6ehzhl/meta_mega_moving_away_from_50gb_free_storage_to/ https://www.reddit.com/r/MEGA/comments/7i4xbr/what_does_this_registration_bonus_means_does_the/
